export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const ADD_POKEMON_FAVORITE = 'ADD_POKEMON_FAVORITE';
export const REMOVE_POKEMON_FAVORITE = 'REMOVE_POKEMON_FAVORITE';
export const CREATE_POKEMON = 'CREATE_POKEMON';
export const CLEAR_POKEMON_DETAIL = 'CLEAR_POKEMON_DETAIL';